config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :items do
    get :iv_821, on: :collection
    get :iv_822, on: :collection
    get :iv_823, on: :collection
  end

  root to: 'items#iv_821'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :day, presence: true

  # after_initialize { p 'initialize' } #Item.new
  # after_save { p 'save' } #Item.create Item.save
  # after_create { p 'create' }
  # after_update { p 'update' }
  # after_destroy { p 'destroy' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def render_403
    render file: 'public/403.html', status: :forbidden
  end

  def render_404
    render file: 'public/404.html', status: :not_found
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :find_item, only: %i[show edit update destroy]
  # before_action :admin?, only: %i[edit]

  def index
    @items = Item.all.order(:number)
    @group = ''
  end

  def create
    item = Item.create(items_params)
    if item.persisted?
      redirect_to items_path
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def new; end

  def show; end

  def edit; end

  def update
    if @item.update(items_params)
      redirect_to item_path
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @item.update(items_params)
      redirect_to items_path
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def is_821
    @items = Item.where('number < 6').order(:number)
    @group = 'ИC-821'
    render :index
  end

  def is_822
    @items = Item.where('number > 5 and number < 11').order(:number)
    @group = 'ИC-822'
    render :index
  end

  def is_823
    @items = Item.where('number > 10 and number <16').order(:number)
    @group = 'ИC-823'
    render :index
  end

  private

  def items_params
    params.permit(:day, :number, :st1, :st2, :st3, :st4, :st5, :st6)
  end

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

  def admin?
    true
    # render_403 unless params[:admin]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/include/main/_notification.html.erb
<% if notice %>
  <p class="notice alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert%></p>
<% end %>

app/views/items/edit.html.erb
<div align="center">
  <h2 class="display-3">Shedule</h2>
</div>

<%= form_tag item_path(@item), method: :put do %>
  <table class="table table-striped" border="2">
    <thead class="thead-dark">
        <tr>
          <th colspan="2"><%= @item.day %></th>
        </tr>
    </thead>
    <tr>
      <td>08:00-09:50</td>
      <td> <%= text_field_tag :st1, @item.st1%></td>
    </tr>
    <tr>
      <td>09:50-11:25</td>
      <td> <%= text_field_tag :st2, @item.st2%></td>
    </tr>
    <tr>
      <td>11:40-13:15</td>
      <td> <%= text_field_tag :st3, @item.st3%></td>
    </tr>
    <tr>
      <td>13:45-15:20</td>
      <td> <%= text_field_tag :st4, @item.st4%></td>
    </tr>
    <tr>
      <td>15:35-17:10</td>
      <td> <%= text_field_tag :st5, @item.st5%></td>
    </tr>
    <tr>
      <td>17:25-19:00</td>
      <td> <%= text_field_tag :st6, @item.st6%></td>
    </tr>
  </table>
  <br/>
  <div align="center">
    <table>
      <tr>
        <td><%= submit_tag "Update", class: "btn btn-large btn-primary" %></td>
<% end %>
        <td><%= button_to 'Back', item_path(@item), method: :get, class: "btn btn-large btn-primary" %></td>
      </tr>
    </table>
  </div>

app/views/items/index.html.erb
<div align="center">
  <h2 class="display-3">Shedule</h2>
</div>

<div align="center">
  <h2 class="display-5"><%= @group %></h2>
</div>

<table class="table table-striped" border="2">
  <thead class="thead-dark">
    <tr>
      <th></th>
      <% @items.each do |item| %>
        <th><%= link_to item.day, item_path(item)%></th>
      <% end %>
    </tr>
  </thead>

  <tr>
    <td>08:00-09:50</td>
    <% @items.each do |item| %>
      <td><%= item.st1 %></td>
    <% end %>
  </tr>
  <tr>
    <td>09:50-11:25</td>
    <% @items.each do |item| %>
      <td><%= item.st2 %></td>
    <% end %>
  </tr>
  <tr>
    <td>11:40-13:15</td>
    <% @items.each do |item| %>
      <td><%= item.st3 %></td>
    <% end %>
  </tr>
  <tr>
    <td>13:45-15:20</td>
    <% @items.each do |item| %>
      <td><%= item.st4 %></td>
    <% end %>
  </tr>
  <tr>
    <td>15:35-17:10</td>
    <% @items.each do |item| %>
      <td><%= item.st5 %></td>
    <% end %>
  </tr>
  <tr>
    <td>17:25-19:00</td>
    <% @items.each do |item| %>
      <td><%= item.st6 %></td>
    <% end %>
  </tr>
</table>
<br/>

<%= render partial: 'layouts/shared/group'%>

<%#= button_to 'new', new_item_path, method: :get%>

app/views/items/new.html.erb
<h2>Create new item</h2>

<%= form_tag items_path, method: :post do %>
  <%= label_tag :day%>
  <%= text_field_tag :day%>
  <ul>
    <li>
      <%= label_tag :number%>
      <%= text_field_tag :number%>
    </li>
    <li>
      <%= label_tag :st1%>
      <%= text_field_tag :st1%>
    </li>
    <li>
      <%= label_tag :st2%>
      <%= text_field_tag :st2%>
    </li>
    <li>
      <%= label_tag :st3%>
      <%= text_field_tag :st3%>
    </li>
    <li>
      <%= label_tag :st4%>
      <%= text_field_tag :st4%>
    </li>
    <li>
      <%= label_tag :st5%>
      <%= text_field_tag :st5%>
    </li>
    <li>
      <%= label_tag :st6%>
      <%= text_field_tag :st6%>
    </li>
  </ul>

  <%= submit_tag "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/show.html.erb
<div align="center">
  <h2 class="display-3">Shedule</h2>
</div>

<table class="table table-striped" border="2">
  <thead class="thead-dark">
    <tr>
      <th colspan="2"><%= @item.day %></th>
    </tr>
  </thead>
  <tr>
    <td>08:00-09:50</td>
    <td><%= @item.st1 %></td>
  </tr>
  <tr>
    <td>09:50-11:25</td>
    <td><%= @item.st2 %></td>
  </tr>
  <tr>
    <td>11:40-13:15</td>
    <td><%= @item.st3 %></td>
  </tr>
  <tr>
    <td>13:45-15:20</td>
    <td><%= @item.st4 %></td>
  </tr>
  <tr>
    <td>15:35-17:10</td>
    <td><%= @item.st5 %></td>
  </tr>
  <tr>
    <td>17:25-19:00</td>
    <td><%= @item.st6 %></td>
  </tr>
</table>

<div align="center">
  <table>
    <tr>
      <% if user_signed_in? %>
        <td><%= button_to 'Edit', edit_item_path, method: :get%></td>
      <% end %>
    </tr>
  </table>
</div>
<br/>

<%= render partial: 'layouts/shared/group'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LessonsShedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- devise -->
      <%= render 'include/auth/auth_header' %>
    <!-- devise -->

    <div class="jumbotron vertical-center">
        <%= render 'include/main/notification' %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_group.html.erb
<div align="center">
  <table>
    <tr>
      <td><%= button_to 'ИВ-821', iv_821_items_path, method: :get, class: "btn btn-large btn-primary"%></td>
      <td><%= button_to 'ИВ-822', iv_822_items_path, method: :get, class: "btn btn-large btn-primary"%></td>
      <td><%= button_to 'ИВ-823', iv_823_items_path, method: :get, class: "btn btn-large btn-primary"%></td>
    </tr>
  </table>
</div>